include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ReachOptions

$(TWEAK_NAME)_FILES = Actions.xm ReachOptions.xm UIDevice+notchedDevice.m
$(TWEAK_NAME) = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk 